# Generated by Django 4.2.1 on 2023-09-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=85)),
                ('email', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
