# Generated by Django 4.2.1 on 2023-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.URLField(default='https://www.127.0.0.1'),
        ),
    ]
