# Generated by Django 4.2.1 on 2023-09-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
