# Generated by Django 4.2.1 on 2023-09-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_alter_order_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='url',
        ),
    ]
